{"name": "Проверка возникновения ошибки при авторизации курьера с неверным паролем", "status": "passed", "steps": [{"name": "Авторизация созданного курьера", "status": "passed", "parameters": [{"name": "login", "value": "'Ninja'"}, {"name": "password", "value": "'4321'"}], "start": 1747235120966, "stop": 1747235121025}], "start": 1747235120966, "stop": 1747235121025, "uuid": "2e04674f-6744-4874-a0da-c583017480f4", "historyId": "4015f1864b6ad30ddd6199d2e7d44d9c", "testCaseId": "4015f1864b6ad30ddd6199d2e7d44d9c", "fullName": "tests.test_couriers.TestLoginCourier#test_login_courier_wrong_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_couriers"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-579T290"}, {"name": "thread", "value": "8216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_couriers"}]}