{"name": "Проверка возникновения ошибки при авторизации курьера с неверным логином", "status": "passed", "steps": [{"name": "Авторизация созданного курьера", "status": "passed", "parameters": [{"name": "login", "value": "'Minja'"}, {"name": "password", "value": "'1234'"}], "start": 1747235120697, "stop": 1747235120760}], "start": 1747235120697, "stop": 1747235120760, "uuid": "e6788026-04b1-4437-99b5-340a4a0b6beb", "historyId": "cd71ecf61a341f80847700d84410563f", "testCaseId": "cd71ecf61a341f80847700d84410563f", "fullName": "tests.test_couriers.TestLoginCourier#test_login_courier_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_couriers"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-579T290"}, {"name": "thread", "value": "8216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_couriers"}]}