{"name": "Проверка возникновения ошибки при авторизации курьера без логина", "status": "passed", "steps": [{"name": "Авторизация созданного курьера", "status": "passed", "parameters": [{"name": "login", "value": "''"}, {"name": "password", "value": "'1234'"}], "start": 1747235121289, "stop": 1747235121342}], "start": 1747235121288, "stop": 1747235121343, "uuid": "f31cd635-9ab5-4126-9f3c-99e22e586cc2", "historyId": "9736e3dc9fbcb42a0bdd4e966cd1c588", "testCaseId": "9736e3dc9fbcb42a0bdd4e966cd1c588", "fullName": "tests.test_couriers.TestLoginCourier#test_login_courier_without_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_couriers"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-579T290"}, {"name": "thread", "value": "8216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_couriers"}]}